#!/usr/bin/env bash
# This script displays its own PID

for pid_dir in /proc/[0-9]*; do
    pid=$(basename "$pid_dir")
    if [ -f "$pid_dir/comm" ]; then
        name=$(<"$pid_dir/comm")
        if echo "$name" | grep -q "bash"; then
            echo "$pid $name"
        fi
    fi
done
