#!/usr/bin/env bash
# This script displays its own PID
for pid in $(ls /proc | grep -E '^[0-9]+$'); do
    if [ -f /proc/"$pid"/comm ]; then
        name=$(cat /proc/"$pid"/comm)
        if echo "$name" | grep -q "bash"; then
            echo "$pid $name"
        fi
    fi
done
